USE [master]
GO
/****** Object:  Database [tandem]    Script Date: 1/3/2023 04:47:36 ******/
CREATE DATABASE [tandem]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'tandem', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\tandem.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'tandem_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\tandem_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [tandem] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [tandem].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [tandem] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [tandem] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [tandem] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [tandem] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [tandem] SET ARITHABORT OFF 
GO
ALTER DATABASE [tandem] SET AUTO_CLOSE ON 
GO
ALTER DATABASE [tandem] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [tandem] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [tandem] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [tandem] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [tandem] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [tandem] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [tandem] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [tandem] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [tandem] SET  ENABLE_BROKER 
GO
ALTER DATABASE [tandem] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [tandem] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [tandem] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [tandem] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [tandem] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [tandem] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [tandem] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [tandem] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [tandem] SET  MULTI_USER 
GO
ALTER DATABASE [tandem] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [tandem] SET DB_CHAINING OFF 
GO
ALTER DATABASE [tandem] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [tandem] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [tandem] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [tandem] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [tandem] SET QUERY_STORE = ON
GO
ALTER DATABASE [tandem] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [tandem]
GO
/****** Object:  User [admin]    Script Date: 1/3/2023 04:47:36 ******/
CREATE USER [admin] WITHOUT LOGIN WITH DEFAULT_SCHEMA=[dbo]
GO
/****** Object:  Table [dbo].[Usuarios]    Script Date: 1/3/2023 04:47:36 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Usuarios](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[nombreYApellido] [nvarchar](70) NOT NULL,
	[usuario] [nvarchar](30) NOT NULL,
	[password] [nvarchar](200) NOT NULL,
	[email] [nvarchar](100) NOT NULL,
	[telefono] [int] NOT NULL,
	[dni] [int] NOT NULL,
	[fechaCreacion] [datetime] NOT NULL,
	[fechaModificacion] [datetime] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET IDENTITY_INSERT [dbo].[Usuarios] ON 
GO
INSERT [dbo].[Usuarios] ([id], [nombreYApellido], [usuario], [password], [email], [telefono], [dni], [fechaCreacion], [fechaModificacion]) VALUES (1, N'Administrador', N'admin', N'admin', N'admin@gmail.com', 1111111, 36000000, CAST(N'2023-03-01T04:45:38.480' AS DateTime), CAST(N'2023-03-01T04:45:38.480' AS DateTime))
GO
SET IDENTITY_INSERT [dbo].[Usuarios] OFF
GO
/****** Object:  Index [UQ__Usuarios__2A16D9454CA06277]    Script Date: 1/3/2023 04:47:36 ******/
ALTER TABLE [dbo].[Usuarios] ADD UNIQUE NONCLUSTERED 
(
	[telefono] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [UQ__Usuarios__AB6E6164550DCF50]    Script Date: 1/3/2023 04:47:36 ******/
ALTER TABLE [dbo].[Usuarios] ADD UNIQUE NONCLUSTERED 
(
	[email] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [UQ__Usuarios__D87608A79CA1CE3F]    Script Date: 1/3/2023 04:47:36 ******/
ALTER TABLE [dbo].[Usuarios] ADD UNIQUE NONCLUSTERED 
(
	[dni] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Usuarios] ADD  DEFAULT (getdate()) FOR [fechaCreacion]
GO
ALTER TABLE [dbo].[Usuarios] ADD  DEFAULT (getdate()) FOR [fechaModificacion]
GO
USE [master]
GO
ALTER DATABASE [tandem] SET  READ_WRITE 
GO
